dist: trusty

sudo: false  # builds will run on Docker infrastructure!

language: scala

scala:
  - 2.12.6

jdk:
  - oraclejdk8
  - openjdk8

branches:
  only:
    - master

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile
